### ISSUE TITLE
Find-Package returns incorrect packagefilename

### ISSUE THREAD

**Issue by jeopal** [OneGet/NuGetProvider#13]
Find-Package returns the value of PackageFilename set equal to the ID concatenated with the Version of the nuget as specified in the nuspec. If the actual filename of the nupkg is different than the ID concatenated with Version, the returned PackageFilename is incorrect and cannot be used for operations such as Remove-Item.

**Comment by jianyunt** [comment]
@jeopal  Package name(id) and version is the way to uniquely identity a NuGet package.
The NuGetProvider extracts the package ID and Version from nuspec and install it on the system.

NuGetpackage format: packageid.version.nupkg

If a package does not follow this NuGet protocol, our NuGetProvider cannot process it properly. This is by design.
